import { Direction, TurnDirection, Items } from '../constants';
import { Exec } from '../command/executor';
import { Success, Result, BlockName, Data } from '../command/result';
export declare const createMoveCommand: (Exec: Exec<Success>) => (direction: Direction) => Promise<import("../command/executor").ErrorMsg | Success>;
export declare const createTurnCommand: (Exec: Exec<Success>) => (direction: TurnDirection) => Promise<import("../command/executor").ErrorMsg | Success>;
export declare const createPlaceCommand: (Exec: Exec<Success>) => (slotNum: number, direction: Direction) => Promise<import("../command/executor").ErrorMsg | Success>;
export declare const createTillCommand: (Exec: Exec<Success>) => (direction: Direction) => Promise<import("../command/executor").ErrorMsg | Success>;
export declare const createAttack: (Exec: Exec<Success>) => (direction: Direction) => Promise<import("../command/executor").ErrorMsg | Success>;
export declare const createCollect: (Exec: Exec<Success>) => (item: Items) => Promise<import("../command/executor").ErrorMsg | Success>;
export declare const createDrop: (Exec: Exec<Success>) => (slotNum: number, quantity: number, direction: Direction) => Promise<import("../command/executor").ErrorMsg | Success>;
export declare const createDropAll: (Exec: Exec<Success>) => (direction: Direction) => Promise<import("../command/executor").ErrorMsg | Success>;
export declare const createDetect: (Exec: Exec<Result>) => (direction: Direction) => Promise<import("../command/executor").ErrorMsg | Result>;
export declare const createInspect: (Exec: Exec<BlockName>) => (direction: Direction) => Promise<import("../command/executor").ErrorMsg | BlockName>;
export declare const createInspectData: (Exec: Exec<Data>) => (direction: Direction) => Promise<import("../command/executor").ErrorMsg | Data>;
export declare const createDetectRedStone: (Exec: Exec<Result>) => (direction: Direction) => Promise<import("../command/executor").ErrorMsg | Result>;
export declare const createGetItemDetail: (Exec: Exec<Result>) => (slotNum: number) => Promise<import("../command/executor").ErrorMsg | Result>;
export declare const createGetItemSpace: (Exec: Exec<Result>) => (slotNum: number) => Promise<import("../command/executor").ErrorMsg | Result>;
export declare const createTransfer: (Exec: Exec<Result>) => (srcslotNum: number, quantity: number, dstslotNum: number) => Promise<import("../command/executor").ErrorMsg | Result>;
export declare const createTpToPlayer: (Exec: Exec<void>) => () => Promise<void | import("../command/executor").ErrorMsg>;
